name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Gradle build
        run: ./gradlew --no-daemon clean buildAll

