name: Publish (manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 0.3.2)"
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION_NAME: ${{ github.event.inputs.version }}
      PUBLISH_URL: ${{ secrets.PUBLISH_URL }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Publish to repo and mavenLocal
        run: ./gradlew --no-daemon publishRemote

