name: Publish Snapshot
on:
  push:
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PUBLISH_URL: ${{ secrets.PUBLISH_URL }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v4
      - name: Publish snapshot
        run: |
          VERSION_NAME="$(date +'%Y.%m.%d-%H%M%S')-SNAPSHOT"
          ./gradlew --no-daemon publish --stacktrace -PVERSION_NAME="$VERSION_NAME"
