name: Publish Snapshot

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Set versions from build-config.properties
        id: v
        run: |
          VER=$(grep '^VERSION_NAME=' build-config.properties | cut -d= -f2)
          if [ -z "$VER" ]; then
            echo "VERSION_NAME missing in build-config.properties"; exit 1
          fi
          echo "VERSION_NAME=${VER}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "CATALOG_VERSION=${VER}-SNAPSHOT" >> $GITHUB_OUTPUT

      # 1) publish versioning first (it provides the plugin used by others)
      - name: Build and Publish Versioning Plugin
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_URL: https://maven.pkg.github.com/${{ github.repository }}
          VERSION_NAME: ${{ steps.v.outputs.VERSION_NAME }}
          CATALOG_VERSION: ${{ steps.v.outputs.CATALOG_VERSION }}
        run: |
          ./gradlew :versioning:build :versioning:publish --no-configuration-cache

      # 2) publish catalog (consumed by build-logic at settings time)
      - name: Build and Publish Catalog
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_URL: https://maven.pkg.github.com/${{ github.repository }}
          VERSION_NAME: ${{ steps.v.outputs.VERSION_NAME }}
          CATALOG_VERSION: ${{ steps.v.outputs.CATALOG_VERSION }}
        run: |
          ./gradlew :catalog:build :catalog:publish --no-configuration-cache

      # 3) finally, publish the convention plugins
      - name: Build and Publish Plugins
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_URL: https://maven.pkg.github.com/${{ github.repository }}
          VERSION_NAME: ${{ steps.v.outputs.VERSION_NAME }}
          CATALOG_VERSION: ${{ steps.v.outputs.CATALOG_VERSION }}
        run: |
          ./gradlew :build-logic:build :build-logic:publish --no-configuration-cache
